-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4CLpc3kB2LRBIj3c
Ds8zWgUwnPjLbbwoGTKYXVZW9GugCgYIKoZIzj0DAQehRANCAARuLv10t+WhFGVJ
/8Oh1TMN/oMq7+pc5DiIA7W1VzKBSB+ToIuVHSQAcREZQbUyceF987C1rVT6SFTV
Y4nLZviO
-----END PRIVATE KEY-----